spring:
  # 搜索引擎
  elasticsearch:
    # 指定连接的主机地址和端口
    uris: http://frp.dzo-lime.ts.net:10004
    # 账号密码
    username: elastic
    password: serverelasticsearch1024
    # 连接超时时间
    connection-timeout: 2s