# 主配置文件，用于包含其他yml配置模块
spring:
  profiles:
    include:
      - redis
      - rabbitmq
      - elasticsearch
  # 连接
  datasource:
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url
    url: jdbc:mysql://www.dzo-lime.ts.net:3306/recruit
    # 用户
    username: recruit
    # 密码
    password: HBryrtKMemc5H64z
    # 连接池
    hikari:
      # 最小空闲连接
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 最大空闲时长
      idle-timeout: 900000
      # 连接的超时时间
      connection-timeout: 3000
      # 检查连接的有效性
      connection-test-query: select 1
#  thymeleaf:
#    enabled: false

mybatis-plus:
  #  configuration:
  #    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      enabled: true
      charset: UTF-8
      force: true