spring:
  data:
    redis:
      # 使用第0个数据库
      database: 1
      # 连接超时时间
      timeout: 1000
      # 密码
      password: "@lldwb_redis"
      # 地址
      host: 100.66.64.40
      # 端口
      port: 7890