spring:
  # 消息队列
  rabbitmq:
    # 连接的主机地址
    addresses: iprus
    # 连接端口
    port: 5672
    # 账号密码
    username: admin
    password: "ca171bc0"
    # 虚拟主机地址
    virtual-host: /
    # 连接超时的时间
    connection-timeout: 5000
##     启用ConfirmCallback（确认消息投递到交换机）
#    publisher-confirm-type: correlated